apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: config-service
          image: roram/config-server:master
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  type: LoadBalancer
  ports:
    - port: 8888
  selector:
    app: config-service